.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TMUSS" "1" "June 2016" "tmuss 0.2.0-alpha" "Tmuss Manual"
.
.SH "NAME"
\fBtmuss\fR \- profile based tmux session management
.
.SH "SYNOPSYS"
\fBtmuss\fR [\fIprofile\fR]
.
.br
\fBtmuss\fR [\-\-version] [\-\-help] [\-l|\-\-list]
.
.SH "DESCRIPTION"
\fBtmuss\fR is a profile based \fBtmux\fR session manager\. It executes a set of commands defined in a profile file, which allows you simple Tmux session management\.
.
.P
In the first form it lists started profiles (active sessions) if no \fIprofile\fR name is given\. Active but detached profiles are marked with a minus sign (\fB\-\fR), active and attached profiles with a plus sign (\fB+\fR)\. It starts a \fBtmux\fR session with the \fIprofile\fR name, or attaches to the \fIprofile\fR session if the session with the \fIprofile\fR name is already started\.
.
.P
The second form prints version, help, or lists available profiles\.
.
.P
Profile sessions are defined by tmuss\.profile(5)\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help\.
.
.TP
\fB\-l\fR, \fB\-\-list\fR
List all available profiles\.
.
.TP
\fB\-\-version\fR
Print program version\.
.
.SH "EXIT STATUS"
0 Success
.
.P
1 General error
.
.P
2 User error
.
.SH "FILES"
Profile files are located under the \fI~/\.config/tmuss/profiles/\fR directory\. See tmuss\.profile(5) for more details\.
.
.SH "BUGS"
Report bugs to <https://github\.com/loonies/tmuss>\.
.
.SH "EXAMPLES"
.
.TP
List started profiles:
.
.IP
$ tmuss
.
.TP
Start or attach the \fIdefault\fR profile:
.
.IP
$ tmuss default
.
.SH "SEE ALSO"
tmuss\.profile(5), tmux(1)
