#!/usr/bin/env bash

# tmuss
#
# Profile based tmux session management
#
# Copyright (C) 2014-2016 Miodrag Tokić
# Released under the MIT License.

set -o errexit
set -o nounset

readonly VERSION="0.2.1"

readonly EXIT_SUCCESS=0
readonly EXIT_EGENERAL=1
readonly EXIT_EUSER=2

readonly profext=".profile"

profdir="$HOME/.config/tmuss/profiles"
workdir="$HOME"
profile=""

usage() {
    cat <<EOF
Usage:
    tmuss [<profile>]
    tmuss [--version] [-h|--help] [-l|--list]

EOF
}

help() {
    usage

    cat <<EOF
Options:
    -h, --help  Display help message
    -l, --list  List profiles
    --version   Display version information

EOF
}

version() {
    cat<<EOF
tmuss version $VERSION

Copyright (C) 2014-2016 Miodrag Tokić.
Released under the MIT License.

EOF
}

# Returns profile status
#
# Arguments:
#   $1  Profile name
#
# Returns:
#   -1  Inactive profile
#    0  Active profile, detached
#    1  Active profile, attached
profile_status() {
    local status

    if status=$(tmux list-sessions 2> /dev/null | grep "^${1}:"); then
        [[ "$status" == *\(attached\) ]] && echo 1 || echo 0
    else
        echo -1
    fi
}

list_profiles() {
    local -a profiles
    local profconf

    for profconf in $(find "$profdir" -type f -printf "%f\n" | sort); do
        profiles+=("${profconf%$profext}")
    done

    if [[ ! -z "${profiles-}" ]]; then
        printf "%s\n" "${profiles[@]}" | column -c $(tput cols)
    fi
}

list_sessions() {
    local -a profiles
    local profile
    local profconf
    local marker

    for profconf in $(find "$profdir" -type f -printf "%f\n" | sort); do
        profile="${profconf%$profext}"

        case $(profile_status "$profile") in
            0) marker="(-)" ;;
            1) marker="(+)" ;;
            *) continue ;;
        esac

        printf -v profile "%s %s" "$profile" "$marker"
        profiles+=("$profile")
    done

    if [[ ! -z "${profiles-}" ]]; then
        printf "%s\n" "${profiles[@]}" | column -c $(tput cols)
    fi
}

main() {
    if [[ $(profile_status "$profile") -eq -1 ]]; then
        local profconf="$profdir/$profile$profext"

        if [[ ! -f "$profconf" ]]; then
            echo "Profile configuration not found: $profile"
            exit $EXIT_EGENERAL
        fi

        tmux new-session -d -c "$workdir" -s "$profile"
        . "$profconf"
    fi

    tmux attach-session -c "$workdir" -t "$profile"
}

if [[ $# -lt 1 ]]; then
    list_sessions
    exit $EXIT_SUCCESS
fi

while [[ $# -ne 0 ]]; do
    case "$1" in
        -h|--h|--he|--hel|--help)
            help
            exit $EXIT_SUCCESS
            ;;
        -l|--list)
            list_profiles
            exit $EXIT_SUCCESS
            ;;
        --version)
            version
            exit $EXIT_SUCCESS
            ;;
        -*)
            usage
            exit $EXIT_EUSER
            ;;
        *)
            [[ -n "$1" ]] && profile="$1"
            ;;
    esac

    shift
done


main

exit $EXIT_SUCCESS
